sudo: required
language: scala
jdk: oraclejdk8
dist: trusty
services:
  - docker
  - postgresql
  - mysql
addons:
  postgresql: "9.6"
branches:
  except:
    - release
    - publish
    - website
cache:
  directories:
    #- $HOME/.ivy2/cache
    - $HOME/.m2
    - $HOME/.sbt
env:
  global:
    - secure: Glt43/THOQFt4rX7PyBj3eEFgRssB20H8wzw/Isj3pXP0pmG8d0jetVta6cA8geMGLsTh3t/nGdMOKa2fkP7cDD2pGZzgeMBPbpXsyWAForKYC+9fa7AUTmUlY82rKIzMpnvBeYj+XrVtS17+jqTSxB7t1OxJsX9VZB0YOxn9SJADLyGeXLlXcmJfBgdA+l1riUMYEJrWZwLKgSOKDr3qO32UAFRcCWPKBeJZ4qwV/cd5+nmtbMERlV3TsWWgtb03eH9ps+nBcobmsyRYpnrWVlYvqUV7rTmibSMuALoeczK8HDUZjy9XMRSPe2RDlzCtF+Pp8Q2VepBJtKSKu3k4yJ6NMbltgtb+uOtx8lIsVk+JIu4sVQuyYHwJBjfPzSmz/JI3EDYiJqgX9Q4MAn0BCj7QBTqEQdZmsoVWo9E5R7XWXRmr97wPnoKtjPAWM5FCuBITlEmzbHMOCwF3+RBqV+6KMEeq7RrEfrE85OpESntJndVdFikupk/JoektxQWV4aNxrkxlnxntsKxpShOcBHIyCzGrimKn8cHpViF4C/LiqORv1XLK4/bmCQ548db1Gidj9G9x0WTCyhvqiavTAEaj+R4p6XrWxS3+za404ZYQc4BRLn/VacVuaihWkf8F2Bj6V9X1LjnSyBcAWGRm6DaJVyXq7Oh9LzH4/iLyPQ=
    - secure: GVYDRNMwVypUDJXUQe9SCobwVCezyPODG4T2sMFZdZ3IjBV3vpPQxG0vKj5LL3HjRULb6D8X60Rsso/EQKSVs6cbRhU3h1Am4tgO/KjUswTcf97RJMk9a+pz+KmEFemJXYatpqK5uusYaJcMoKj5D4FeR2Z1FQjgLVV5y6dqAZc+lBzGq2l3QJbBgdwgIb7PLPBszdajpO5LZ3rcxKm+VvvittFqCCNA6V8NINnByByYpxy+BRm2JGrbOiDWzNC41RVbOY/xsRkOAHFKKJofh3sSHf/YAVyavCGi0nwmBevsoGS9Lmt9wGPydvuW7mQ58QODxjlpKoidohQRg81TY/rutl+Ul0a3xVFmTNVwK5dqfBekfwZBI7esBat864LdoWXViH93eQHbkYANUMMb14z5TBWprmAwRdUAUhVXxI201bYFpHTRl8ejBvtT/x0B38CRYd3cM2qjKNkhuOq3G2bCcU1iSW5Kn8U8M+sKI8rXkNtzqSKlQzPXznFhmVybNUh8K6FysIaPDwdtkfnzq9Obw8p1fLcHBts1BeaPxzF28GnTV/nsvTV44VF1sLJJ9kep7YlGzNfNM/eTianlQ1TZozVp+z4sAuytRkYoNgC+NpMnnwdqUk74AvKw2ExRHZbMLtMlKvcliV9etzdiaC0ZbKIFCjS1QFOFB2mpDaI=
    - secure: cq/0b2mHyfkpNtoecmJBhsq37vySkzeaH0TN06jAtW9/zGkm5yaIJkPUCdlJmW0on/xgXLCTvrx17nuRXQJmNpO32KfUOPfn7VIKS054Y8s86z61dKarWthTruNEosIdnmp88lV+V9lsjmAlYZv23u0yMDx4U34FYumPrH14eb27gGd/Xc7+LZpMYf3okxGPRtdxZ5KRO05v9dHcR3IthITixL26M6Z2VUb79fXkMiQ5Z17zh8sh1elS6AnE8SkcLYAefHhdJP18vFx3dmMlYY7m+qwfUmZ3YCZjUUYxA1Z+dnH5/mRNww4Se47TZFmoyHycq+P29znH+P7fSN5TnzTd6B5yPzIjFFTogv7BlPOgpq67J7vKeEyJ7mTYa5br84wnIIw1RJOltzhn2DO3YhXGysPzw8icz1RTlOASW86kUBAGiCzHW9iQGk2wll0ARohHSplahN8Qyb5vtUnF9Qep7fS6DTUHqAFCXiS1g7PEmvTD0ns5j+GNXLUy56LMrotpyV+zO5p8822Vu6315dbDkj7+znh+XTXG5we0AZIEAHK/F3BXy3URWmMdnrowPvlMMB20LLGvxOyaZMQsqBxYypHeKXqDMy9+M16LMJdUQRFCQFFunyGedHLJFyucs3ao6L0sxUdirXKFeoXnuB1QhLHQOphwhENuz1OLWmk=
    - secure: YWJ9ho4mwXjy4GrnbjehDlP5wFA6P8KLZMb+jOCEFNI9wKSiKzUUeIqGNog6Q9KCHE+RMEFz/kqE+7jNhhOgGGv0mRF0RVfHL0SkamhD0NMxiC1vITk3+oqMi/v1sK/V88WbfM4+1sAcFqV7yoptyWw/Db7U/MdLcRZaVe2zMz6s4P811CZjpT2Y/EkwxWcxejTCxptAvAkIfrgIyI28xW9hgA9oWvQJjD42ShKd445AC9qNq8E2cY8ukFIMik/FNHYWQMmdUTYOqX68O6fn2lPcIayPNCl0UuY6L9DB0KS0ZxrItX6/0JQU/CR8iFHWxshACvxLAMLUofPl/0QVkoSVaCGrKCX8WpjQ4K2FV/xiXa6xPXSFcI4RRsGkpXe3S6BHdWdH7whEsLDhvIJN3WQREWYqujXNi2imCO08+N0/GuDxfIcCzkrsEZYk5d1h8HQTk6Ml9ahhbL5EbrgEO6z8C/cLoSwebeYPeO7Wlw8y1f0pT8yIMH0cAI0PrdUzhQOgSgMUZGgntCynHyJymwtlHV7y829qsxvf3M0IpjCwK3VAdQLQKt2evFOT2hIbubpzvR6u26zeflpiMr/U8/uZnu3XYCPFLwkAZEDLb1LNfDiXOZY+cG+aX0R/m3hPDv5G5iH0OCTCwJ/usGSRMxdhwgQqltXrhGLUkvKcy8w=
jobs:
  include:
    - stage: build
      if: type != pull_request
      script: ./build/build.sh db
      scala: 2.11.12
      name: "Databases 2.11 - MySQL, Postgres, Sqlite, H2, SQL Server, Oracle"
    - stage: build
      script: ./build/build.sh db
      scala: 2.12.10
      name: "Databases 2.12 - MySQL, Postgres, Sqlite, H2, SQL Server, Oracle"
    - stage: build
      script: ./build/build.sh db
      scala: 2.13.2
      name: "Databases 2.13 - MySQL, Postgres, Sqlite, H2, SQL Server, Oracle"

    - stage: build
      if: type != pull_request
      script: ./build/build.sh js
      scala: 2.11.12
      name: "Databases 2.11 - JavaScript"
    - stage: build
      script: ./build/build.sh js
      scala: 2.12.10
      name: "Databases 2.12 - JavaScript"
    - stage: build
      script: ./build/build.sh js
      scala: 2.13.1
      name: "Databases 2.13 - JavaScript"

    - stage: build
      if: type != pull_request
      script: ./build/build.sh async
      scala: 2.11.12
      name: "Async, Finagle, NDBC 2.11 - MySQL, Postgres, Sqlite, H2, SQL Server, Oracle"
    - stage: build
      script: ./build/build.sh async
      scala: 2.12.10
      name: "Async, Finagle, NDBC 2.12 - MySQL, Postgres, Sqlite, H2, SQL Server, Oracle"
    - stage: build
      script: ./build/build.sh async
      scala: 2.13.2
      name: "Async, Finagle, NDBC 2.13 - MySQL, Postgres, Sqlite, H2, SQL Server, Oracle"

    - stage: build
      if: type != pull_request
      script: ./build/build.sh codegen
      scala: 2.11.12
      name: "Code Generator 2.11 - MySQL, Postgres, Sqlite, H2, SQL Server, Oracle"
    - stage: build
      if: type != pull_request
      script: ./build/build.sh codegen
      scala: 2.12.10
      name: "Code Generator 2.12 - MySQL, Postgres, Sqlite, H2, SQL Server, Oracle"
    - stage: build
      if: type != pull_request
      script: ./build/build.sh codegen
      scala: 2.13.2
      name: "Code Generator 2.13 - MySQL, Postgres, Sqlite, H2, SQL Server, Oracle"

    - stage: build
      if: type != pull_request
      script: ./build/build.sh bigdata
      scala: 2.11.12
      name: "BigData Databases 2.11 - Cassandra, OrientDB, Spark"
    - stage: build
      script: ./build/build.sh bigdata
      scala: 2.12.10
      name: "BigData Databases 2.12 - Cassandra, OrientDB, Spark"
    - stage: build
      script: ./build/build.sh bigdata
      scala: 2.13.2
      name: "BigData Databases 2.13 - Cassandra, OrientDB, Spark"

    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.11 base"
      script:
        - ./build/release.sh 211 base
    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.11 db"
      script:
        - ./build/release.sh 211 db
    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.11 js"
      script:
        - ./build/release.sh 211 js
    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.11 async"
      script:
        - ./build/release.sh 211 async
    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.11 codegen"
      script:
        - ./build/release.sh 211 codegen
    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.11 bigdata"
      script:
        - ./build/release.sh 211 bigdata

    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.12 base"
      script:
        - ./build/release.sh 212 base
    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.12 db"
      script:
        - ./build/release.sh 212 db
    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.12 js"
      script:
        - ./build/release.sh 212 js
    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.12 async"
      script:
        - ./build/release.sh 212 async
    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.12 codegen"
      script:
        - ./build/release.sh 212 codegen
    - stage: release
      if: type != pull_request
      scala: 2.12.6
      name: "Release 2.12 bigdata"
      script:
        - ./build/release.sh 212 bigdata

    - stage: release
      if: type != pull_request
      scala: 2.13.2
      name: "Release 2.13 base"
      script:
        - ./build/release.sh 213 base
    - stage: release
      if: type != pull_request
      scala: 2.13.2
      name: "Release 2.13 db"
      script:
        - ./build/release.sh 213 db
    - stage: release
      if: type != pull_request
      scala: 2.13.2
      name: "Release 2.13 js"
      script:
        - ./build/release.sh 213 js
    - stage: release
      if: type != pull_request
      scala: 2.13.2
      name: "Release 2.13 async"
      script:
        - ./build/release.sh 213 async
    - stage: release
      if: type != pull_request
      scala: 2.13.2
      name: "Release 2.12 codegen"
      script:
        - ./build/release.sh 213 codegen
    - stage: release
      if: type != pull_request
      scala: 2.13.2
      name: "Release 2.13 bigdata"
      script:
        - ./build/release.sh 213 bigdata

    - stage: publish
      if: type != pull_request AND (branch = master OR branch =~ /re-release.*/)
      scala: 2.12.6
      name: "Publish"
      script:
        - ./build/publish.sh
