postgres:
  image: postgres
  ports:
    - "5432"
  environment:
    - POSTGRES_USER=postgres


mysql:
  image: mysql
  ports:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=quill_test
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes

cassandra:
  image: cassandra:2.1
  ports:
    - "9042"
    - "9160"
    - "7199"
    - "7001"
    - "7000"

setup:
  image: quill/build:latest
  links:
    - postgres:postgres
    - mysql:mysql
    - cassandra:cassandra
  volumes:
    - ./:/app
  command:
    - ./setup.sh
  working_dir: /app

sbt:
  image: 1science/sbt:0.13.8-oracle-jre-8
  command: sbt
  links:
    - postgres:postgres
    - mysql:mysql
    - cassandra:cassandra
  volumes:
    - ./:/app
    - ~/.ivy2:/root/.ivy2
    - ~/.m2:/root/.m2
