name: CI

on:
  pull_request: {}
  push:
    branches:
      - master
      - sbt-ci-release
    # Do not activate CI on tags for now. For releases, run the build the initial release build
    # tags:
    #   - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SCALA_VERSION: ${{ matrix.scala }}
      POSTGRES_PASSWORD: postgres
      MYSQL_PASSWORD: root

    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.x, 2.13.x, 3.3.x]
        module: [base, db, js, async, codegen, bigdata]
        include:
          - scala: 2.12.x
            scala_short: 212
            scala_short_dot: 2.12
          - scala: 2.13.x
            scala_short: 213
            scala_short_dot: 2.13
          - scala: 3.3.x
            scala_short: 33
            scala_short_dot: 3.3
        exclude:
          # For now, only do the `base` build for Scala 3
          - scala: 3.3.x
            module: db
          - scala: 3.3.x
            module: js
          - scala: 3.3.x
            module: async
          - scala: 3.3.x
            module: codegen
          - scala: 3.3.x
            module: bigdata
          # For other modules, `base` build is already included
          - scala: 2.12.x
            module: base
          - scala: 2.13.x
            module: base

    name: Build ${{matrix.scala_short_dot}} - ${{matrix.module}}

    steps:
    - uses: actions/checkout@v4.0.0
    - name: Cache sbt
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/coursier
          ~/.sbt
        key: ${{ runner.os }}-${{matrix.scala}}-${{matrix.module}}-${{ hashFiles('**/build.sbt') }}

    - name: Setup Java and Scala
      uses: actions/setup-java@v3.12.0
      with:
        distribution: temurin
        java-version: '8'
        check-latest: true

    - name: Build modules
      run: |
        echo "SCALA_VERSION='$SCALA_VERSION'"
        ./build/build.sh ${{ matrix.module }}
      env:
        SCALA_VERSION: ${{ matrix.scala }}

  release:
    if: ${{github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Setup Java and Scala
        uses: actions/setup-java@v3.12.0
        with:
          distribution: temurin
          java-version: '8'
          check-latest: true
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
