name: Scala Steward

# This workflow will launch everyday at 00:00
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  scala-steward:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      # See
      #  - https://github.com/zio/generate-github-app-token
      #  - https://github.com/zio/zio-sbt/blob/main/.github/workflows/ci.yml#L123
      - name: Generate Token
        id: generate-token
        uses: zio/generate-github-app-token@v1.0.0
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.61.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
